stages:
  - validate
  - test

# Lint js files.
lint-js:
 image: node
 stage: validate
 tags:
   - docker
 script:
   - npm install -g eslint
   - find $CI_PROJECT_DIR -type f -name '*.js' -print0 | xargs -0 -n1 -P4 eslint --ignore-pattern "**/*.min.js" | (! grep -v "No syntax errors detected" )

# Performs unit testing.
unit-test:
  variables:
    DB_URL: mongodb://mongo:27017
  services:
    - mongo
  image: node
  stage: test
  tags:
    - docker
  script:
    - npm i -g mocha
    - npm i -g nyc
    - npm i .
    - nyc --reporter=text-summary npm t
