stages:
  - validate
  - test

# Lint js files.
lint-js:
 image: node
 stage: validate
 tags:
   - docker
 script:
   - npm install -g eslint
   - eslint --ignore-pattern "**/*.min.js" $CI_PROJECT_DIR

# Performs unit testing.
unit-test:
  variables:
    DB_URL: mongodb://mongo:27017
  services:
    - mongo
  image: node
  stage: test
  tags:
    - docker
  script:
    - npm i -g mocha
    - npm i -g nyc
    - npm i .
    - nyc --reporter=text-summary npm t
